### ISSUE TITLE
[ Migrate ] AppModel Area - Feature Tests

### ISSUE THREAD

**Issue by dipeshmsft** [dotnet/wpf-test#68]
Subareas of AppModel

- [ ] ApplicationTests
- [x] CommonDialogs
- [x] Frame
- [x] Journal
- [ ] MessageBoxTests
- [x] Navigation
- [x] NavigationWindow
- [x] pagefunctions
- [ ] Security
- [ ] SplashScreen
- [ ] TransitionElement
- [ ] WindowTests
- [ ] WindowTestsSxS

**Comment by rchauhan18** [comment]
Current Total: 137 test cases
